// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using teploob.Data;

#nullable disable

namespace teploob.Migrations
{
    [DbContext(typeof(MyApplicationContex))]
    partial class MyApplicationContexModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("teploob.Data.InputData", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("B")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DateAdd")
                        .HasColumnType("TEXT");

                    b.Property<double>("O")
                        .HasColumnType("REAL");

                    b.Property<double>("Tbol")
                        .HasColumnType("REAL");

                    b.Property<double>("Tnt")
                        .HasColumnType("REAL");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.Property<double>("exp1")
                        .HasColumnType("REAL");

                    b.Property<double>("mexp")
                        .HasColumnType("REAL");

                    b.Property<double>("tmal")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("InputDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
